# A docker compose file for building docker file and defining DB_KEY env variable used for Firestore DB
# Author: Nathaniel Mason

version: "3.8"

services:
    time_series_app:
        build: . # Period means current directory, which is where our Dockerfile is located
        image: time_series_app
        command: python flask_Proj1.py
        ports:
            - 5001:5000
        environment:
            - DB_KEY
